// Ingest a new standalone calculator (the React-in-<script type="text/babel">
// HTML the author ships, which mounts to #root via CDN React/ReactDOM/Tailwind)
// and regenerate src/main.jsx — the Vite source for the drop-in build.
//
// It does three swaps and nothing else, so the component logic stays verbatim:
//   1. `const { useState, … } = React;`           → ESM imports + the CSS string
//   2. (component body, untouched)
//   3. `ReactDOM.createRoot(#root).render(<X/>)`   → Shadow-DOM mount of <X>
//
// Usage:  node ingest.mjs [path/to/standalone.html]
//         With no path, it picks the most recently modified .html in sources/ —
//         so the flow is: drop the author's file in sources/, then `bun run ingest`.
// Then:   bun run build
//
// It REPLACES src/main.jsx (backing up the old one to src/main.jsx.bak). If the
// new file doesn't match the expected shape it stops with a clear error rather
// than emitting something broken. src/widget.css is the styling source of truth
// (Ubuntu @theme etc.) and is NOT touched — if the author changes the Tailwind
// theme/config in the HTML <head>, mirror that into widget.css by hand.

import { readFileSync, writeFileSync, existsSync, copyFileSync, readdirSync, statSync } from "node:fs";
import { resolve, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));

// Default source: the newest .html/.htm in sources/.
function newestInSources() {
  const dir = resolve(root, "sources");
  if (!existsSync(dir)) return null;
  const files = readdirSync(dir)
    .filter((f) => /\.html?$/i.test(f))
    .map((f) => resolve(dir, f))
    .sort((a, b) => statSync(b).mtimeMs - statSync(a).mtimeMs);
  return files[0] || null;
}

const SRC = process.argv[2] ? resolve(root, process.argv[2]) : newestInSources();
const OUT = resolve(root, "src/main.jsx");

const die = (msg) => {
  console.error(`ingest: ${msg}`);
  process.exit(1);
};

if (!SRC) die("no source given and no .html found in sources/ — pass a path or drop a file in sources/");
if (!existsSync(SRC)) die(`source file not found: ${SRC}`);
console.log(`ingest: reading ${relative(root, SRC)}`);
const html = readFileSync(SRC, "utf8");

// 1. Extract the component <script> (Babel or module).
const scriptMatch = html.match(/<script\b[^>]*type=["'](?:text\/babel|module)["'][^>]*>([\s\S]*?)<\/script>/i);
if (!scriptMatch) die('no <script type="text/babel"> (or type="module") block found in the HTML');
let code = scriptMatch[1];

// 2. Pull the React hooks out of `const { useState, useMemo, … } = React;`
//    so we can import exactly those (some versions add useEffect/useRef/etc.).
const hooksMatch = code.match(/const\s*\{([^}]*)\}\s*=\s*React\s*;?/);
const hooks = hooksMatch
  ? hooksMatch[1].split(",").map((s) => s.trim()).filter(Boolean)
  : [];
if (hooksMatch) code = code.replace(hooksMatch[0], "");

// 3. Find the rendered root component, then slice off the whole mount tail.
//    Handles:  ReactDOM.createRoot(...).render(React.createElement(X))
//              const root = ReactDOM.createRoot(...); root.render(<X .../>)
//              ReactDOM.render(<X/>, el)
let component = null;
const patterns = [
  /\.render\(\s*React\.createElement\(\s*([A-Za-z_$][\w$]*)\s*[),]/, // .render(React.createElement(X))
  /\.render\(\s*<\s*([A-Za-z_$][\w$]*)[\s/>]/, //                       .render(<X .../>)
  /ReactDOM\.render\(\s*<\s*([A-Za-z_$][\w$]*)[\s/>]/, //               ReactDOM.render(<X/>, ...)
];
for (const re of patterns) {
  const m = code.match(re);
  if (m) {
    component = m[1];
    break;
  }
}
if (!component) die("could not find the rendered root component (expected ReactDOM.createRoot(...).render(...))");

// Remove the entire mount block by slicing the code at the earliest mount
// marker — avoids paren-balancing issues and can't touch component-internal
// code, since the mount is conventionally the last thing in the script.
const markers = [
  /\/\/[^\n]*RENDER[^\n]*/i, //                    a "// ─ RENDER ─" banner
  /(?:const\s+[\w$]+\s*=\s*)?(?:ReactDOM\.)?createRoot\s*\(/, // createRoot(...)
  /ReactDOM\.render\s*\(/, //                       ReactDOM.render(...)
];
const cut = markers
  .map((re) => code.search(re))
  .filter((i) => i >= 0)
  .reduce((a, b) => Math.min(a, b), Infinity);
if (cut === Infinity) die("found a render() but no mount statement to strip");
code = code.slice(0, cut).trim();

const hookImport = hooks.length ? `, { ${hooks.join(", ")} }` : "";

const main = `// Kita-Zuschuss Rechner — Volt Karlsruhe
// GENERATED by ingest.mjs from ${relative(root, SRC)} — re-run \`node ingest.mjs [file]\` to refresh.
// Built with Vite into a single self-contained drop-in fragment
// (see vite.config.mjs + build-droppable.mjs). No runtime CDNs.
import React${hookImport} from "react";
import { createRoot } from "react-dom/client";
// Imported as a string (not injected globally) so we can place it inside the
// widget's Shadow DOM, where it can't collide with the host page's styles.
import cssText from "./widget.css?inline";

${code}

// ─── MOUNT (Shadow DOM) ──────────────────────────────────────
const MOUNT_ID = "kita-zuschuss-rechner-root";
function mount() {
  // querySelectorAll (not getElementById) so multiple pastes on one page each
  // render; the data-mounted guard stops a node from double-mounting.
  document.querySelectorAll("#" + MOUNT_ID).forEach((host) => {
    if (host.dataset.mounted === "true") return;
    host.dataset.mounted = "true";
    // Render inside a Shadow DOM with the stylesheet scoped to it, so the
    // widget's Tailwind cannot leak onto — or be leaked into by — the host page.
    const shadow = host.shadowRoot || host.attachShadow({ mode: "open" });
    const style = document.createElement("style");
    style.textContent = cssText;
    shadow.appendChild(style);
    const container = document.createElement("div");
    shadow.appendChild(container);
    createRoot(container).render(React.createElement(${component}));
  });
}
if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", mount);
} else {
  mount();
}
`;

if (existsSync(OUT)) copyFileSync(OUT, OUT + ".bak");
writeFileSync(OUT, main, "utf8");
console.log(
  `ingest: wrote src/main.jsx (component <${component}>, hooks: ${hooks.join(", ") || "none"}). ` +
    `Backed up previous to src/main.jsx.bak. Now run: bun run build`
);
